- name: Create gtran Dirs
  sudo: no
  file: path=/home/{{ansible_ssh_user}}/.emacs.d/site-lisp/gtran-emacs state=directory
- name: Create gore Dirs
  sudo: no
  file: path=/home/{{ansible_ssh_user}}/.emacs.d/gore-mode state=directory
- name: Create twit Dirs
  sudo: no
  file: path=/home/{{ansible_ssh_user}}/.emacs.d/twittering-mode state=directory
- name: git clone gore-mode package
  sudo: no
  git: repo=https://github.com/yasukun/gore-mode.git dest=/home/{{ansible_ssh_user}}/.emacs.d/gore-mode
- name: git clone gtran package
  sudo: no
  git: repo=https://github.com/yasukun/gtran-emacs.git dest=/home/{{ansible_ssh_user}}/.emacs.d/site-lisp/gtran-emacs
- name: git clone twit package
  sudo: no
  git: repo=https://github.com/hayamiz/twittering-mode.git dest=/home/{{ansible_ssh_user}}/.emacs.d/twittering-mode
- name: git clone 2ch proxy
  sudo: no
  git: repo=https://github.com/yama-natuki/2chproxy.pl.git dest=/home/{{ansible_ssh_user}}/github/2chproxy.pl
