---
- name: Create jupyter_root Dir
  sudo: no
  file: path=/home/{{ansible_ssh_user}}/jupyter_root state=directory
- name: Create .jupyter Dir
  sudo: no
  file: path=/home/{{ansible_ssh_user}}/.jupyter state=directory
- name: make git clone dir
  become: yes
  become_user: "{{ansible_ssh_user}}"
  file: path='/home/{{ansible_ssh_user}}/.pyenv' state=directory
- name: git clone
  become: yes
  become_user: "{{ansible_ssh_user}}"
  git: repo=https://github.com/pyenv/pyenv.git dest=/home/{{ansible_ssh_user}}/.pyenv
- name: define env variables 1
  become: yes
  become_user: "{{ansible_ssh_user}}"
  lineinfile: >
    dest='/home/{{ansible_ssh_user}}/.bashrc'
    line='export PYENV_ROOT="$HOME/.pyenv"'
    backup=yes
- name: define env variables 2
  become: yes
  become_user: "{{ansible_ssh_user}}"
  lineinfile: >
    dest='/home/{{ansible_ssh_user}}/.bashrc'
    line='export PATH="$PYENV_ROOT/bin:$PATH"'
    backup=yes
- name: define env variables 3
  become: yes
  become_user: "{{ansible_ssh_user}}"
  lineinfile: >
    dest='/home/{{ansible_ssh_user}}/.bashrc'
    line='eval "$(pyenv init -)"'
    backup=yes
- name: edit jupyter_notebook_config.py 1
  become: yes
  become_user: "{{ansible_ssh_user}}"
  lineinfile: >-
    dest='/home/{{ansible_ssh_user}}/.jupyter/jupyter_notebook_config.py'
    line="c.NotebookApp.allow_origin = '*'"
    state=present
    create=yes
- name: edit jupyter_notebook_config.py 2
  become: yes
  become_user: "{{ansible_ssh_user}}"
  lineinfile: >-
    dest='/home/{{ansible_ssh_user}}/.jupyter/jupyter_notebook_config.py'
    line="c.NotebookApp.base_url = '/jupyter'"
- name: edit jupyter_notebook_config.py 3
  become: yes
  become_user: "{{ansible_ssh_user}}"
  lineinfile: >-
    dest='/home/{{ansible_ssh_user}}/.jupyter/jupyter_notebook_config.py'
    line="c.NotebookApp.ip = '*'"
- name: edit jupyter_notebook_config.py 4
  become: yes
  become_user: "{{ansible_ssh_user}}"
  lineinfile: >-
    dest='/home/{{ansible_ssh_user}}/.jupyter/jupyter_notebook_config.py'
    line="c.NotebookApp.notebook_dir = '/home/{{ansible_ssh_user}}/jupyter_root'"
- name: edit jupyter_notebook_config.py 5
  become: yes
  become_user: "{{ansible_ssh_user}}"
  lineinfile: >-
    dest='/home/{{ansible_ssh_user}}/.jupyter/jupyter_notebook_config.py'
    line="c.NotebookApp.open_browser = False"
